# -*- coding: utf-8 -*-
"""capstone project.ipynb

Automatically generated by 
"""

!pip install groq

import time
import os
import json
import plotly.graph_objects as go
from groq import Groq   # xAI official Grok API client

os.environ["GROK_API_KEY"] = "GROQ API KEY"

client = Groq(api_key=os.getenv("GROK_API_KEY"))

MODEL = "llama-3.3-70b-versatile"     # or "grok-2-mini" (faster & cheaper)
CHAT_DURATION = 300   # 5 minutes


def grok_generate(prompt):
    try:
        completion = client.chat.completions.create(
            model=MODEL,
            messages=[{"role": "user", "content": prompt}]
        )
        return completion.choices[0].message.content
    except Exception as e:
        print("❌ Grok Error:", e)
        return "Error: Grok API unavailable."

print("💬 AI Wellness Companion (GROK) — Chat for 5 mins or type 'exit'\n")

conversation = []
start_time = time.time()

while True:
    user_msg = input("You: ")

    if user_msg.lower() in ["exit", "quit", "bye"]:
        print("\n🔍 Generating Emotional Analysis...\n")
        break

    conversation.append({"role": "user", "text": user_msg})

    reply = grok_generate(user_msg)
    print("Bot:", reply)

    conversation.append({"role": "bot", "text": reply})

    if time.time() - start_time >= CHAT_DURATION:
        print("\n⏳ 5 minutes complete! Generating Emotional Analysis...\n")
        break


conv_text = "\n".join([f"{msg['role']}: {msg['text']}" for msg in conversation])

analysis_prompt = f"""
Analyse the following conversation and assign a score from 0–100 for each metric.
Conversation:
{conv_text}

Return STRICT JSON ONLY:

{{
 "emotional_stability": <number>,
 "stress_level": <number>,
 "optimism": <number>,
 "social_connectedness": <number>,
 "cognitive_clarity": <number>,
 "energy_level": <number>,
 "summary": "<short explanation>"
}}
"""

analysis_output = grok_generate(analysis_prompt)
print("Raw Analysis Output:\n", analysis_output, "\n")


def safe_parse_json(text):
    try:
        return json.loads(text)
    except:
        try:
            start = text.find("{")
            end = text.rfind("}")
            if start != -1 and end != -1:
                return json.loads(text[start:end+1])
        except:
            pass
    return {
        "emotional_stability": 0,
        "stress_level": 0,
        "optimism": 0,
        "social_connectedness": 0,
        "cognitive_clarity": 0,
        "energy_level": 0,
        "summary": "Analysis failed — invalid JSON."
    }

analysis_json = safe_parse_json(analysis_output)


labels = [
    "Emotional Stability",
    "Stress Level",
    "Optimism",
    "Social Connectedness",
    "Cognitive Clarity",
    "Energy Level"
]

values = [
    analysis_json["emotional_stability"],
    analysis_json["stress_level"],
    analysis_json["optimism"],
    analysis_json["social_connectedness"],
    analysis_json["cognitive_clarity"],
    analysis_json["energy_level"]
]

fig = go.Figure()
fig.add_trace(go.Scatterpolar(r=values, theta=labels, fill='toself'))
fig.update_layout(
    title="🧠 Emotional Profile (Grok Analysis)",
    polar=dict(radialaxis=dict(visible=True, range=[0, 100])),
    showlegend=False
)
fig.show()

print("\n📝 Emotional Summary:")
print(analysis_json["summary"])
